networks:
  three-tier-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  csv-data:
    driver: local

services:

  #DATABASE SERVICE
  mysql:
    build: ./Database
    container_name: database-container
    restart: unless-stopped
    networks:
      - three-tier-network
    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    
    ports:
      - "3306:3306"
    
    volumes:
      - mysql-data:/var/lib/mysql
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: backend-container
    restart: unless-stopped
    networks:
      - three-tier-network
    
    ports:
      - "3000:3000"
    
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: user_db
      DB_PORT: 3306
    
    volumes:
      - /home/reem/lab6_data:/app/data:rw
      - csv-data:/app/data/backup
    
    depends_on:
      - mysql

  frontend:
    build: ./Frontend
    container_name: frontend-container
    restart: unless-stopped
    networks:
      - three-tier-network
    
    ports:
      - "5173:5173"
    
    depends_on:
      - backend